- name: Build and push image to Huawei SWR  # 构建并推送镜像到华为云SWR
      run: |
        while IFS= read -r line || [ -n "$line" ]; do  # 逐行读取images.txt文件中的内容
            # 忽略空行与注释
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                continue
            fi
        
            # 拉取镜像
            echo "docker pull $line"
            sudo docker pull $line
        
            # 获取镜像名称和版本
            image_name=$(echo "$line" | awk -F':' '{print $1}')
            version=$(echo "$line" | awk -F':' '{print $2}')
        
            # 打标签
            new_image="${HUAWEI_SWR_ENDPOINT}/${HUAWEI_SWR_NAMESPACE}/${image_name}:${version}"
            echo "docker tag $line $new_image"
            sudo docker tag $line $new_image
        
            # 推送镜像
            echo "docker push $new_image"
            sudo docker push $new_image
        
            # 清理本地镜像
            echo "docker rmi $line $new_image"
            sudo docker rmi $line $new_image
        
        done < images.txt
